/*
 * This file is part of Spectra - https://github.com/trqxyz/ai_server
 * Copyright (C) 2026 KaelusAI
 *
 * Spectra is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Spectra is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
// automatically generated by the FlatBuffers compiler, do not modify
package trqxyz.spectra.flatbuffers

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.Table
import java.nio.ByteBuffer
import java.nio.ByteOrder

@Suppress("unused", "UnnecessaryParentheses")
class TickData : Table() {
  fun __init(_i: Int, _bb: ByteBuffer) {
    __reset(_i, _bb)
  }

  fun __assign(_i: Int, _bb: ByteBuffer): TickData {
    __init(_i, _bb)
    return this
  }

  fun deltaYaw(): Float {
    val o = __offset(4)
    return if (o != 0) bb.getFloat(o + bb_pos) else 0.0f
  }

  fun deltaPitch(): Float {
    val o = __offset(6)
    return if (o != 0) bb.getFloat(o + bb_pos) else 0.0f
  }

  fun accelYaw(): Float {
    val o = __offset(8)
    return if (o != 0) bb.getFloat(o + bb_pos) else 0.0f
  }

  fun accelPitch(): Float {
    val o = __offset(10)
    return if (o != 0) bb.getFloat(o + bb_pos) else 0.0f
  }

  fun jerkPitch(): Float {
    val o = __offset(12)
    return if (o != 0) bb.getFloat(o + bb_pos) else 0.0f
  }

  fun jerkYaw(): Float {
    val o = __offset(14)
    return if (o != 0) bb.getFloat(o + bb_pos) else 0.0f
  }

  fun gcdErrorYaw(): Float {
    val o = __offset(16)
    return if (o != 0) bb.getFloat(o + bb_pos) else 0.0f
  }

  fun gcdErrorPitch(): Float {
    val o = __offset(18)
    return if (o != 0) bb.getFloat(o + bb_pos) else 0.0f
  }

  class Vector : BaseVector() {
    fun __assign(_vector: Int, _elementSize: Int, _bb: ByteBuffer): Vector {
      __reset(_vector, _elementSize, _bb)
      return this
    }

    fun get(j: Int): TickData {
      return get(TickData(), j)
    }

    fun get(obj: TickData, j: Int): TickData {
      return obj.__assign(__indirect(__element(j), bb), bb)
    }
  }

  companion object {
    @JvmStatic
    fun ValidateVersion() {
      Constants.FLATBUFFERS_25_2_10()
    }

    @JvmStatic
    fun getRootAsTickData(_bb: ByteBuffer): TickData {
      return getRootAsTickData(_bb, TickData())
    }

    @JvmStatic
    fun getRootAsTickData(_bb: ByteBuffer, obj: TickData): TickData {
      _bb.order(ByteOrder.LITTLE_ENDIAN)
      return obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)
    }

    @JvmStatic
    fun createTickData(
      builder: FlatBufferBuilder,
      deltaYaw: Float,
      deltaPitch: Float,
      accelYaw: Float,
      accelPitch: Float,
      jerkPitch: Float,
      jerkYaw: Float,
      gcdErrorYaw: Float,
      gcdErrorPitch: Float,
    ): Int {
      builder.startTable(8)
      addGcdErrorPitch(builder, gcdErrorPitch)
      addGcdErrorYaw(builder, gcdErrorYaw)
      addJerkYaw(builder, jerkYaw)
      addJerkPitch(builder, jerkPitch)
      addAccelPitch(builder, accelPitch)
      addAccelYaw(builder, accelYaw)
      addDeltaPitch(builder, deltaPitch)
      addDeltaYaw(builder, deltaYaw)
      return endTickData(builder)
    }

    @JvmStatic
    fun startTickData(builder: FlatBufferBuilder) {
      builder.startTable(8)
    }

    @JvmStatic
    fun addDeltaYaw(builder: FlatBufferBuilder, deltaYaw: Float) {
      builder.addFloat(0, deltaYaw, 0.0)
    }

    @JvmStatic
    fun addDeltaPitch(builder: FlatBufferBuilder, deltaPitch: Float) {
      builder.addFloat(1, deltaPitch, 0.0)
    }

    @JvmStatic
    fun addAccelYaw(builder: FlatBufferBuilder, accelYaw: Float) {
      builder.addFloat(2, accelYaw, 0.0)
    }

    @JvmStatic
    fun addAccelPitch(builder: FlatBufferBuilder, accelPitch: Float) {
      builder.addFloat(3, accelPitch, 0.0)
    }

    @JvmStatic
    fun addJerkPitch(builder: FlatBufferBuilder, jerkPitch: Float) {
      builder.addFloat(4, jerkPitch, 0.0)
    }

    @JvmStatic
    fun addJerkYaw(builder: FlatBufferBuilder, jerkYaw: Float) {
      builder.addFloat(5, jerkYaw, 0.0)
    }

    @JvmStatic
    fun addGcdErrorYaw(builder: FlatBufferBuilder, gcdErrorYaw: Float) {
      builder.addFloat(6, gcdErrorYaw, 0.0)
    }

    @JvmStatic
    fun addGcdErrorPitch(builder: FlatBufferBuilder, gcdErrorPitch: Float) {
      builder.addFloat(7, gcdErrorPitch, 0.0)
    }

    @JvmStatic
    fun endTickData(builder: FlatBufferBuilder): Int {
      return builder.endTable()
    }
  }
}
